### ISSUE TITLE
delivery mode

### ISSUE THREAD

**Issue by akoenig** [CompassPHS/tortoise#12]
Awesome library with a nice elegant interface. Thanks for abstracting the hazzle with amqplib away. I have one question though. Would it be possible to pass custom options when publishing against an exchange? I'm looking for passing the "persistent" [deliveryMode](http://www.squaremobius.net/amqp.node/channel_api.html#channel_publish) which results in persisted message between broker restarts. Do you have any plans to support custom attributes?

**Comment by bbedwell** [comment]
@akoenig Actually, this is already supported. A `.publish(..)` chained from a `.exchange(..)` will have the following interface:

`publish(routingKey, message, [options])`

Where `options` is the same as amqplib (that is, in fact, what we end up calling under the abstraction).

So, you would do something like this:

````
tortoise
  .exchange('my-exchange', 'direct', { durable:false })
  .publish('routing.key', { Hello: 'World' }, { deliveryMode: 2 });
````

And here is the called code for reference: 
https://github.com/CompassPHS/tortoise/blob/2282caaecf3f827d004257d3d87f58603493091f/lib/exchange.js#L27

**Comment by akoenig** [comment]
@bbedwell Brilliant! Scanned the codebase just a little bit. My fault that I missed that option passing.

Yeah, reflecting that in the README would be great.

Thanks :)
